import { db } from '../src/config/supabase.js'
const lines = await db.from('metro_lines').select('*')
console.log('=== LINES ===')
console.log(JSON.stringify(lines.data, null, 2))
const stations = await db.from('stations').select('id,station_name,station_code,line_id').order('station_name')
console.log('=== STATIONS ===')
console.log(JSON.stringify(stations.data, null, 2))
const mach = await db.from('machines').select('id,machine_id,station_id,capacity,current_stock,status').limit(30)
console.log('=== MACHINES (first 30) ===')
console.log(JSON.stringify(mach.data, null, 2))
const ref = await db.from('refill_records').select('*').order('created_at', { ascending: false }).limit(3)
console.log('=== RECENT REFILLS (columns) ===')
if (ref.data) console.log(JSON.stringify(ref.data, null, 2))
else console.log('error', ref.error)
